# Generated by Django 4.1.7 on 2023-06-13 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_offer_izd_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izd',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='izds', to='assignments.offer'),
            preserve_default=False,
        ),
    ]
