# Generated by Django 4.1.7 on 2023-09-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_fileuploadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GUID', models.CharField(blank=True, max_length=255, null=True)),
                ('json_in', models.TextField(blank=True, null=True)),
                ('its_parce', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'InData',
                'verbose_name_plural': 'InData',
            },
        ),
        migrations.AlterField(
            model_name='fileuploadimage',
            name='hash',
            field=models.CharField(default='44LWD', max_length=255, verbose_name='hash'),
        ),
    ]
