# Generated by Django 5.1.4 on 2024-12-19 19:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Доп. Изделие',
                'verbose_name_plural': 'Доп. Изделия',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Уникальный UUID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена старая')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена новая')),
                ('order_pdf', models.FileField(blank=True, null=True, upload_to='media/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF сметы')),
                ('additionals', models.ManyToManyField(related_name='orders', to='smeta.additional', verbose_name='Дополнительные')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='smeta.manager', verbose_name='Менеджер')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='smeta.office', verbose_name='Офис')),
            ],
            options={
                'verbose_name': 'Смета | Заказ',
                'verbose_name_plural': 'Сметы | Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(verbose_name='Уникальный идентификатор пользователя')),
                ('liked', models.BooleanField(verbose_name='Оценка: Нрав./Не нрав.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-Время создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='smeta.order', verbose_name='Смета / Заказ')),
            ],
            options={
                'verbose_name': 'Оценка - Сметы | Заказа',
                'verbose_name_plural': 'Оценки - Сметы | Заказа',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(verbose_name='Идентификатор')),
                ('system', models.CharField(max_length=255, verbose_name='Система')),
                ('series', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
                ('base_color', models.CharField(max_length=255, verbose_name='Цвет основания')),
                ('inner_color', models.CharField(max_length=255, verbose_name='Цвет внутренний')),
                ('outer_color', models.CharField(max_length=255, verbose_name='Цвет внешний')),
                ('handles', models.CharField(max_length=255, verbose_name='Ручки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('image', models.TextField(verbose_name='Изображение')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('options', models.ManyToManyField(related_name='products', to='smeta.option', verbose_name='Опции')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='smeta.product', verbose_name='Изделия'),
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(related_name='orders', to='smeta.service', verbose_name='Услуги'),
        ),
    ]

