# Generated by Django 5.1.4 on 2024-12-06 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Дополнительный',
                'verbose_name_plural': 'Дополнительные',
                'unique_together': {('name', 'quantity', 'cost')},
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'unique_together': {('name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
                'unique_together': {('name', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(unique=True, verbose_name='Идентификатор')),
                ('system', models.CharField(max_length=255, verbose_name='Система')),
                ('series', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
                ('base_color', models.CharField(max_length=255, verbose_name='Цвет основания')),
                ('inner_color', models.CharField(max_length=255, verbose_name='Цвет внутренний')),
                ('outer_color', models.CharField(max_length=255, verbose_name='Цвет внешний')),
                ('handles', models.CharField(max_length=255, verbose_name='Ручки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('image', models.TextField(verbose_name='Изображение')),
                ('options', models.ManyToManyField(related_name='products', to='smeta.option', verbose_name='Опции')),
            ],
            options={
                'verbose_name': 'Издение',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'unique_together': {('name', 'cost')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена старая')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена новая')),
                ('additionals', models.ManyToManyField(related_name='orders', to='smeta.additional', verbose_name='Дополнительные')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='smeta.manager', verbose_name='Менеджер')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='smeta.office', verbose_name='Офис')),
                ('products', models.ManyToManyField(related_name='orders', to='smeta.product', verbose_name='Изделия')),
                ('services', models.ManyToManyField(related_name='orders', to='smeta.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Смета | Заказ',
                'verbose_name_plural': 'Сметы | Заказы',
            },
        ),
    ]
