# Generated by Django 5.1.4 on 2024-12-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='identifier',
            field=models.IntegerField(verbose_name='Идентификатор'),
        ),
    ]
