# Generated by Django 5.1.4 on 2025-01-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additionals',
            field=models.ManyToManyField(blank=True, related_name='orders', to='smeta.additional', verbose_name='Дополнительные'),
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='orders', to='smeta.service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='handles',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ручки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='products', to='smeta.option', verbose_name='Опции'),
        ),
    ]
