# Generated by Django 5.1.4 on 2025-01-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0002_alter_order_additionals_alter_order_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Номер'),
        ),
    ]
