# Generated by Django 5.1.4 on 2024-12-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0002_alter_product_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
