# Generated by Django 5.1.4 on 2024-12-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0003_alter_option_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
