# Generated by Django 5.1.4 on 2025-01-29 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0003_alter_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=4, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 29, 20, 54, 18, 331607, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
