# Generated by Django 5.1.4 on 2025-02-23 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0004_order_code_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Код аналитики')),
            ],
            options={
                'verbose_name': 'Код метрики',
                'verbose_name_plural': 'Код метрики',
            },
        ),
        migrations.CreateModel(
            name='ChatCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Код чата')),
            ],
            options={
                'verbose_name': 'Код чата',
                'verbose_name_plural': 'Код чата',
            },
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True, verbose_name='Название файла')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
