# Generated by Django 5.1.4 on 2024-12-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0004_alter_manager_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additional',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='manager',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='office',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
    ]
