# Generated by Django 4.2.13 on 2025-03-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0005_analyticscode_chatcode_logfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.PositiveIntegerField(default=30, verbose_name='Срок хранения (дней)')),
            ],
            options={
                'verbose_name': 'Настройка логирования',
                'verbose_name_plural': 'Настройки логирования',
            },
        ),
        migrations.CreateModel(
            name='ScriptCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.TextField(verbose_name='Код скрипта')),
                ('placement', models.CharField(choices=[('head_start', 'В начале head'), ('head_end', 'В конце head'), ('body_start', 'В начале body'), ('body_end', 'В конце body')], max_length=20, verbose_name='Место размещения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Скрипт',
                'verbose_name_plural': 'Скрипты',
            },
        ),
        migrations.CreateModel(
            name='TemplateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('html_template', models.TextField(verbose_name='HTML шаблон')),
                ('css_template', models.TextField(verbose_name='CSS шаблон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шаблон сметы',
                'verbose_name_plural': 'Шаблоны сметы',
            },
        ),
        migrations.CreateModel(
            name='WebhookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL вебхука')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Настройка вебхука',
                'verbose_name_plural': 'Настройки вебхука',
            },
        ),
        migrations.CreateModel(
            name='RawJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Исходный JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_json', to='smeta.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Исходный JSON',
                'verbose_name_plural': 'Исходные JSON',
            },
        ),
    ]
