# Generated by Django 5.1.4 on 2024-12-06 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0005_alter_additional_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='smeta.manager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='smeta.office', verbose_name='Офис'),
        ),
    ]
