# Generated by Django 5.1.4 on 2024-12-09 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0006_alter_order_manager_alter_order_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF сметы'),
        ),
    ]
