# Generated by Django 5.1.4 on 2024-12-10 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0007_order_order_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(verbose_name='Уникальный идентификатор пользователя')),
                ('liked', models.BooleanField(verbose_name='Оценка: Нрав./Не нрав.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-Время создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='smeta.order', verbose_name='Смета / Заказ')),
            ],
            options={
                'verbose_name': 'Оценка - Сметы | Заказа',
                'verbose_name_plural': 'Оценки - Сметы | Заказа',
            },
        ),
    ]
