# Generated by Django 4.2.13 on 2025-03-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0007_logfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True, verbose_name='Ключевое слово')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
            ],
            options={
                'verbose_name': 'Ключевое слово лога',
                'verbose_name_plural': 'Ключевые слова логов',
                'ordering': ['-usage_count', 'keyword'],
            },
        ),
        migrations.RemoveField(
            model_name='logfilter',
            name='keywords',
        ),
        migrations.AddField(
            model_name='logfilter',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='filters', to='smeta.logkeyword', verbose_name='Ключевые слова'),
        ),
    ]
