# Generated by Django 5.1.4 on 2024-12-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0008_orderrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additional',
            options={'verbose_name': 'Доп. Изделие', 'verbose_name_plural': 'Доп. Изделия'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
