# Generated by Django 5.1.4 on 2024-12-18 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0009_alter_additional_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
