# Generated by Django 4.1.7 on 2023-06-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('text_small', models.TextField(blank=True, null=True)),
                ('text_big', models.TextField(blank=True, null=True)),
                ('price_crossed', models.CharField(blank=True, max_length=100, null=True)),
                ('term', models.CharField(blank=True, max_length=255, null=True)),
                ('price_izd', models.CharField(blank=True, max_length=100, null=True)),
                ('price_kompl', models.CharField(blank=True, max_length=100, null=True)),
                ('price_service', models.CharField(blank=True, max_length=100, null=True)),
                ('manager', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offer',
            },
        ),
        migrations.CreateModel(
            name='Izd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('har', models.CharField(blank=True, max_length=100, null=True)),
                ('cout', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.offer')),
            ],
            options={
                'verbose_name': 'Izd',
                'verbose_name_plural': 'Izd',
            },
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('sticker', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.offer')),
            ],
            options={
                'verbose_name': 'Additional',
                'verbose_name_plural': 'Additional',
            },
        ),
    ]
