# Generated by Django 4.1.7 on 2023-07-05 06:04

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_additional_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default='TOIVE', max_length=255, verbose_name='hash')),
                ('file_img', models.ImageField(blank=True, null=True, upload_to=assignments.models.upload_to, verbose_name='file')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'ФайлыИзображений',
                'verbose_name_plural': 'ФайлыИзображений',
            },
        ),
    ]
