# Generated by Django 4.1.7 on 2024-10-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_alter_fileuploadimage_hash_alter_indata_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('json_in', models.TextField(blank=True, null=True)),
                ('its_parce', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
            ],
            options={
                'verbose_name': 'Wh',
                'verbose_name_plural': 'Wh',
            },
        ),
        migrations.AlterField(
            model_name='fileuploadimage',
            name='hash',
            field=models.CharField(default='88E6K', max_length=255, verbose_name='hash'),
        ),
        migrations.AlterField(
            model_name='indata',
            name='hash',
            field=models.CharField(blank=True, default='8E0XX', max_length=255, null=True),
        ),
    ]
