# Generated by Django 5.1.2 on 2024-10-29 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_wh_alter_fileuploadimage_hash_alter_indata_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='fileuploadimage',
            name='hash',
            field=models.CharField(default='16TC5', max_length=255, verbose_name='hash'),
        ),
        migrations.AlterField(
            model_name='indata',
            name='hash',
            field=models.CharField(blank=True, default='TTAAC', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField()),
                ('system', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('base_color', models.CharField(max_length=100)),
                ('inner_color', models.CharField(max_length=100)),
                ('outer_color', models.CharField(max_length=100)),
                ('handles', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('image', models.TextField()),
                ('options', models.ManyToManyField(related_name='products', to='assignments.option')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.manager')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.office')),
                ('products', models.ManyToManyField(related_name='orders', to='assignments.product')),
                ('services', models.ManyToManyField(related_name='orders', to='assignments.service')),
                ('supplements', models.ManyToManyField(related_name='orders', to='assignments.supplement')),
            ],
        ),
    ]
