# Generated by Django 5.1.2 on 2024-10-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_manager_office_option_service_supplement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional',
            name='offer',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='FileUploadImage',
        ),
        migrations.RemoveField(
            model_name='izd',
            name='offer',
        ),
        migrations.AlterField(
            model_name='indata',
            name='hash',
            field=models.CharField(blank=True, default='8T4T5', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Additional',
        ),
        migrations.DeleteModel(
            name='Izd',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
