# Generated by Django 5.1.2 on 2024-10-29 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_remove_additional_offer_delete_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='assignments.office'),
        ),
        migrations.AlterField(
            model_name='indata',
            name='hash',
            field=models.CharField(blank=True, default='99B13', max_length=255, null=True),
        ),
    ]
