# Generated by Django 5.1.2 on 2024-10-29 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_manager_office_alter_indata_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supplements',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.order'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.order'),
        ),
        migrations.AlterField(
            model_name='indata',
            name='hash',
            field=models.CharField(blank=True, default='A94X3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.office'),
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Supplement',
        ),
    ]
