# Generated by Django 5.1.2 on 2024-10-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_remove_order_supplements_remove_order_products_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.AlterField(
            model_name='indata',
            name='hash',
            field=models.CharField(blank=True, default='8B5KP', max_length=255, null=True),
        ),
    ]
