# Generated by Django 5.1.2 on 2024-10-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_alter_indata_hash_option_delete_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indata',
            name='hash',
            field=models.CharField(blank=True, default='K4K62', max_length=255, null=True),
        ),
    ]
