# Generated by Django 5.1.2 on 2024-10-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_alter_indata_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indata',
            name='hash',
            field=models.CharField(blank=True, default='T6BM9', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UpSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.order')),
            ],
        ),
    ]
